// Generated by generate-config.js
const imageData = [
  {
    "id": 1,
    "title": "IMG 8836",
    "lowRes": "images/IMG_8836-lowres.jpg",
    "highRes": "images/IMG_8836-highres.jpg"
  },
  {
    "id": 2,
    "title": "IMG 4761",
    "lowRes": "images/IMG_4761-lowres.jpg",
    "highRes": "images/IMG_4761-highres.jpg"
  },
  {
    "id": 3,
    "title": "RajGupta 11 213",
    "lowRes": "images/RajGupta_11_213-lowres.JPG",
    "highRes": "images/RajGupta_11_213-highres.JPG"
  },
  {
    "id": 4,
    "title": "Fury",
    "lowRes": "images/Fury-lowres.JPG",
    "highRes": "images/Fury-highres.JPG"
  },
  {
    "id": 5,
    "title": "IMG 4761",
    "lowRes": "images/IMG_4761-lowres.jpg",
    "highRes": "images/IMG_4761-highres.jpg"
  },
  {
    "id": 6,
    "title": "IMG 5309",
    "lowRes": "images/IMG_5309-lowres.jpg",
    "highRes": "images/IMG_5309-highres.jpg"
  },
  {
    "id": 7,
    "title": "IMG 7165",
    "lowRes": "images/IMG_7165-lowres.JPG",
    "highRes": "images/IMG_7165-highres.JPG"
  },
  {
    "id": 8,
    "title": "RajGupta 11 047A",
    "lowRes": "images/RajGupta_11_047A-lowres.jpg",
    "highRes": "images/RajGupta_11_047A-highres.jpg"
  },
];

// Export for module usage
if (typeof module !== 'undefined') {
  module.exports = imageData;
}