// Generated by generate-config.js
const imageData = [
  {
    "title": "IMG 8836",
    "lowRes": "images/IMG_8836-lowres.jpg",
    "highRes": "images/IMG_8836-highres.jpg"
  },
  {
    "title": "Fury",
    "lowRes": "images/Fury-lowres.JPG",
    "highRes": "images/Fury-highres.JPG"
  },
  {
    "title": "IMG 4761",
    "lowRes": "images/IMG_4761-lowres.jpg",
    "highRes": "images/IMG_4761-highres.jpg"
  },
  {
    "title": "IMG 7163 (1)",
    "lowRes": "images/IMG_7163 (1)-lowres.jpg",
    "highRes": "images/IMG_7163 (1)-highres.jpg"
  },
  {
    "title": "IMG 5309",
    "lowRes": "images/IMG_5309-lowres.jpg",
    "highRes": "images/IMG_5309-highres.jpg"
  },
  {
    "title": "IMG 7165",
    "lowRes": "images/IMG_7165-lowres.JPG",
    "highRes": "images/IMG_7165-highres.JPG"
  },
  {
    "title": "IMG 8341",
    "lowRes": "images/IMG_8341-lowres.jpg",
    "highRes": "images/IMG_8341-highres.jpg"
  },
  {
    "title": "RajGupta 11 047A",
    "lowRes": "images/RajGupta_11_047A-lowres.jpg",
    "highRes": "images/RajGupta_11_047A-highres.jpg"
  },
  {
    "title": "RajGupta 11 131A",
    "lowRes": "images/RajGupta_11_131A-lowres.JPG",
    "highRes": "images/RajGupta_11_131A-highres.JPG"
  },
  {
    "title": "RajGupta 11 213",
    "lowRes": "images/RajGupta_11_213-lowres.JPG",
    "highRes": "images/RajGupta_11_213-highres.JPG"
  }
];

// Export for module usage
if (typeof module !== 'undefined') {
  module.exports = imageData;
}